###############################################################################
# Tijolo configuration file, use with ♥️
#
# If you mess up with this and want to load the defaults, just delete this
# file.
###############################################################################

# If true, start language server only when opening a file with a language server, otherwise
# scan project and start all possible language servers
# Default: false
lazy_start_language_servers = false

# Ignore these directories when loading any project.
# Default: ["node_modules", "tmp/cache"]
ignored_dirs = ["node_modules", "tmp/cache"]

# Set to true to removing trailing white space on save
# Default: true
trim_trailing_white_space_on_save = true

# Tijolo log level, can be: trace, debug, info, notice, warn, error, fatal, none
# Default: "info"
log_level = "info"

# Any valid strings accepted by gtk_accelerator_parse is a valid shortcut
#
# From GTK docs:
#
# The format looks like "<Control>a" or "<Shift><Alt>F1" or "<Release>z" (the last one is
# for key release).
#
# The parser is fairly liberal and allows lower or upper case, and also abbreviations such
# as "<Ctl>" and "<Ctrl>". For character keys the name is not the symbol, but the lowercase
# name, e.g. one would use "<Ctrl>minus" instead of "<Ctrl>-".
[shortcuts]
close_view       = "<Control>W"
comment_code     = "<Control>slash"
find             = "<Control>F"
find_next        = "F3"
find_prev        = "<Shift>F3"
fullscreen       = "F11"
goto_definition  = "F2"
goto_line        = "<Control>G"
new_file         = "<Control>N"
open_file        = "<Control>O"
save_view_as     = "<Control><Shift>S"
save_view        = "<Control>S"
show_git_locator = "<Alt>G"
show_locator     = "<Control>P"
sort_lines       = "F9"
show_hide_sidebar     = "<Alt>0"
focus_editor          = "<Alt>1"
show_hide_output_pane = "<Alt>2"

# Language servers are started using stdio communication, to know all possible language IDs
# list file names /usr/share/gtksourceview-4/language-specs/
[language-servers]
# SCry, not very good but is what we have for Crystal
crystal = "scry"

# SolarGraph for Ruby, slow but awesome.. but you probably need to change something here if you need to
# run it with bundle exec, rvm do, etc...
ruby = "solargraph stdio"

# Bash language server
# https://github.com/bash-lsp/bash-language-server
sh = "bash-language-server start"
