name: build
on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check
      - name: Install packages
        run: sudo apt-get update && sudo apt-get -qy install make libeditorconfig-dev libgirepository1.0-dev libgit2-dev libgtksourceview-4-dev libvte-2.91-dev libyaml-dev xvfb
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: make test
      - name: Compile it
        run: make debug
